---
kind: pipeline
type: docker
name: syntax

steps:
- name: run flake8
  image: python
  commands:
    - pip3 install flake8
    - flake8 --ignore=E265,E266,E402,E501  # comments, import order, line-length

---
kind: pipeline
type: docker
name: test

steps:
- name: unit tests
  image: python
  commands:
    - pip3 install pytest
    - pip3 install pytest-cov
    - export PYTHONPATH=$(pwd)/src
    - pytest -v --cov=plafosim tests/unit_tests

---
kind: pipeline
type: docker
name: run

steps:
  - name: default values
    image: python
    commands:
      - pip3 install funcy
      - ./plafosim.py

---
kind: pipeline
type: docker
name: correctness

steps:
- name: statistical tests
  image: dbuse/sumo-python:3.8-buster-1_1_0
  commands:
    - apt update
    - apt install time
    - pip3 install funcy
    - pip3 install matplotlib
    - pip3 install pandas
    - pip3 install statistics
    - ./scripts/compare2sumo.sh
