---
kind: pipeline
type: docker
name: syntax

steps:
- name: flake8
  image: python
  commands:
    - pip3 install flake8
    - flake8 --ignore=E265,E266,E402,E501  # comments, import order, line-length

---
kind: pipeline
type: docker
name: test

steps:
- name: unittests
  image: python
  commands:
    - pip3 install pytest
    - pip3 install pytest-cov
    - export PYTHONPATH=$(pwd)/src
    - pytest -v --cov=plafosim tests/unit_tests

- name: coverage
  image: python
  environment:
    HOST:
      from_secret: WWW_FTP_HOST
    USERNAME:
      from_secret: WWW_FTP_USER
    PASSWORD:
      from_secret: WWW_FTP_PASSWORD
  commands:
    - pip3 install coverage
    - pip3 install coverage-badge
    - coverage-badge -o coverage.svg
    - apt update
    - apt install lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; put coverage.svg;"

---
kind: pipeline
type: docker
name: execution

steps:
  - name: run
    image: python
    commands:
      - pip3 install funcy
      - ./plafosim.py --penetration 0.5  # test both vehicle types

---
kind: pipeline
type: docker
name: correctness

steps:
- name: statistical tests
  image: dbuse/sumo-python:3.8-buster-1_1_0
  commands:
    - apt update
    - apt install time
    - pip3 install funcy
    - pip3 install matplotlib
    - pip3 install pandas
    - pip3 install statistics
    - ./scripts/compare2sumo.sh

trigger:
  branch:
    - master
    - develop
