---
kind: pipeline
type: docker
name: test

steps:
- name: unit tests
  image: python
  commands:
    - pip3 install pytest
    - pip3 install pytest-cov
    - export PYTHONPATH=$(pwd)/src
    - pytest -v --cov=plafosim tests/unit_tests

---
kind: pipeline
type: docker
name: run

steps:
  - name: default values
    image: python
    commands:
      - pip3 install funcy
      - ./plafosim.py
