---
kind: pipeline
type: docker
name: testing

steps:
- name: unit tests
  image: python
  commands:
    - pip3 install pytest
    - pip3 install pytest-cov
    - export PYTHONPATH=$(pwd)/src
    - pytest -v --cov=plafosim tests/unit_tests
