---
kind: pipeline
type: docker
name: testing

steps:
- name: run pytest
  image: python
  commands:
    - pip install pytest
    - pip install pytest-cov
    - export PYTHONPATH=$(pwd)/src
    - pytest -v --cov=plafosim
